name: smonsg
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.5.0+1
  lottie: ^3.1.2
  animate_do: ^3.3.4
  email_validator: ^3.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.2.1
  flutter_sequence_animation: ^4.0.0
  flutter_animate: ^4.5.0
  video_player: ^2.9.1
  flutter_secure_storage: ^9.2.2
  blur: ^4.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  flutter_blurhash: ^0.8.2
  file_picker: ^8.0.6
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  liquid_swipe: ^3.1.0
  cupertino_icons: ^1.0.6
  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^1.0.1
  light: ^3.0.1
  permission_handler: ^11.3.1
  cached_network_image: ^3.0.0
  sqflite: ^2.2.0+4
  path_provider: ^2.0.9
  flutter_cache_manager: ^3.0.0
  socket_io_client: ^2.0.0
  encrypt: ^5.0.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_image_compress: ^1.1.0
  image: ^4.2.0
  timeago: ^3.1.0
  shared_preferences: ^2.2.3
  flutter_sound: ^9.1.6
  camera: ^0.10.0+2
  agora_rtc_engine: ^6.3.2
  agora_rtm: ^1.5.9
  flutter_dotenv: ^5.0.2
  videosdk: ^1.1.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/profile_image.jpg
    - assets/loading1.json
    - assets/welcome.mp4
    - assets/success.json

# Add the dependency_overrides section here, at the same level as dependencies, dev_dependencies, and flutter
dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  js: ^0.7.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  material_color_utilities: ^0.12.0
  meta: ^1.15.0
  test_api: ^0.7.3
  vm_service: ^14.2.4
  string_scanner: ^1.3.0
  firebase_messaging_platform_interface: ^4.5.41
  firebase_messaging_web: 3.8.11
  rxdart: 0.28.0
  web: 1.0.0