// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzS5caLP2ULFySbq542xFnaYomIxjMgU',
    appId: '1:96936363102:web:4ed68812912a4b456ba0cf',
    messagingSenderId: '96936363102',
    projectId: 'smonsg-knr',
    authDomain: 'smonsg-knr.firebaseapp.com',
    storageBucket: 'smonsg-knr.appspot.com',
    measurementId: 'G-9Y7ERWY97F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fBaPfyiWpvOcm1QwV9rpS3LOLU-1BGs',
    appId: '1:96936363102:android:91bc888c3da852e26ba0cf',
    messagingSenderId: '96936363102',
    projectId: 'smonsg-knr',
    storageBucket: 'smonsg-knr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi03UqQ-2BdcuPRL_z8WT0S7bZFXq9hWM',
    appId: '1:96936363102:ios:2a321b7ff546689a6ba0cf',
    messagingSenderId: '96936363102',
    projectId: 'smonsg-knr',
    storageBucket: 'smonsg-knr.appspot.com',
    iosBundleId: 'com.example.smonsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi03UqQ-2BdcuPRL_z8WT0S7bZFXq9hWM',
    appId: '1:96936363102:ios:2a321b7ff546689a6ba0cf',
    messagingSenderId: '96936363102',
    projectId: 'smonsg-knr',
    storageBucket: 'smonsg-knr.appspot.com',
    iosBundleId: 'com.example.smonsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyzS5caLP2ULFySbq542xFnaYomIxjMgU',
    appId: '1:96936363102:web:736c5ef3e19792846ba0cf',
    messagingSenderId: '96936363102',
    projectId: 'smonsg-knr',
    authDomain: 'smonsg-knr.firebaseapp.com',
    storageBucket: 'smonsg-knr.appspot.com',
    measurementId: 'G-5ZXBKYL4XW',
  );
}
